### ISSUE TITLE
Notification Lasts Too Long

### ISSUE THREAD

**Issue by Uzer1** [MARNUTUX/lympha-cookies#3]
**The lympha notification is useful, but lasts too long.** 
It takes up too much of the screen space. 
Since there is nothing important to read in it, it makes sense to minimize HideAfter in its js file. I tried adding this parameter to XPI, but my version of Firefox won't accept the modified XPI even after disabling xp signature in settings. 
So, I'll be waiting for the hide delay to be modified by creators.

**Comment by m-arrieta-r** [comment]
What version do you use?

**Comment by Uzer1** [comment]
0.3.1

**Comment by Uzer1** [comment]
Firefox 51.0.1

**Comment by m-arrieta-r** [comment]
The notifications were disabled by default, thanks for the feedback
